const parseDate = (dateStr) => {
  // Parse "Month YYYY" format more explicitly
  const [month, year] = dateStr.split(' ');
  const monthIndex = {
    'January': 0, 'February': 1, 'March': 2, 'April': 3,
    'May': 4, 'June': 5, 'July': 6, 'August': 7,
    'September': 8, 'October': 9, 'November': 10, 'December': 11
  }[month];
  
  return new Date(parseInt(year), monthIndex, 1).getTime();
};

const articles = [
  {
    id: 1,
    title: 'DSI wins student organization of the year',
    image: '/images/newsletter/grso-org-year25/1.jpeg',
    articleImage: '/images/newsletter/grso-org-year25/2.jpeg',
    date: 'March 2025',
    category: 'Awards',
    featured: true,
    description: `DSI was named Organization of the Year (GRSO) at this year's Student Involvement Awards across all UF student organizations! 🎉\n\nWe are honored and humbled to share this with all of you who have continuously supported us, whether by attending our workshops, competing alongside us at hackathons, or helping fund our initiatives.\n\nWe also want to congratulate our newly elected External Vice President, My Pham, on winning the Emerging Gator Award, which recognizes outstanding underclassmen leaders. We are so proud to have My on our team.\n\nThis award is a testament to the work we have been doing and the core belief that knowledge should be accessible to all.`,
  },
  {
    id: 2,
    title: "DSI member's chatbot SAMSARA wins AI hackathon",
    image: '/images/newsletter/samsara25/1.jpeg',
    articleImage: '/images/newsletter/samsara25/1.jpeg',
    date: 'February 2025',
    category: 'Competition',
    featured: false,
    description: `Join us in congratulating one of our students, Kalim Qazi, in winning first place nationally at Sentient's Hackathon!\n\n Across 7 days of public access, Samsara logged nearly 24 hours of total usage and received over 2,800 messages, all from organic traffic. We are extremely proud of you and of your hard work!`,
  },
  {
    id: 3,
    title: "DSI members win Best Visualization at DataFest 2025",
    image: '/images/newsletter/datafest25/1.jpg',
    articleImage: '/images/newsletter/datafest25/1.jpg',
    date: 'February 2025',
    category: 'Competition',
    featured: false,
    description: `Matheus Kunzler Maldaner, Ishan Kumthekar, Aadhitya Vijaisenthi, Aaron Goffstein and Adit Potta won Best Visualization at DataFest 2025!`,
  },
  {
    id: 4,
    title: "DSI members win Most Popular Award at 2024 AI Days Hackathon",
    image: '/images/newsletter/ai-days24/1.jpg',
    articleImage: '/images/newsletter/ai-days24/2.jpg',
    date: 'December 2024',
    category: 'Competition',
    featured: false,
    description: `Raul Valle, Landon Nayab, Matheus Kunzler Maldaner and Stephen Wormald won Most Popular Award for their FPGA Implementation of a Differentiable Logic Gate Neural Network.`,
  },
  {
    id: 5,
    title: "DSI members win Best AI Hack at SwampHacks 2025",
    image: '/images/newsletter/swamphacks25/1.jpg',
    articleImage: '/images/newsletter/swamphacks25/1.jpg',
    date: 'January 2025',
    category: 'Competition',
    featured: false,
    description: `DSI members Matheus Kunzler Maldaner, Kristian O'Connor, Danush Singla and Pranav Bhargava won the Best AI Hack at SwampHacks 2025, University of Florida's Largest Hackathon, by programming an interface to visualize the inner workings of Differentiable Logic Gate Neural Networks.`,
  },
  {
    id: 6,
    title: "DSI members win Most Popular Award at ShellHacks 2024",
    image: '/images/newsletter/shellhacks24/1.jpg',
    articleImage: '/images/newsletter/shellhacks24/2.jpg',
    date: 'September 2024',
    category: 'Competition',
    featured: false,
    description: `Thanks to the financial support of Dr. Juan Gilbert and CISE and AIIRI's collaboration, DSI was able to send 54 students to compete at ShellHacks 2024, Florida's largest hackathon with over 700 participants! DSI members Raul Valle, Matheus Kunzler Maldaner, Emily Jiji and Evan Partidas won the Most Popular project and several other UF students won specific company track prizes.`,
  },
  {
    id: 7,
    title: "DSI and UFIT hosted Nvidia Deep Learning Workshop",
    image: '/images/newsletter/nvidia-dli24/1.jpg',
    articleImage: '/images/newsletter/nvidia-dli24/2.jpg',
    date: 'November 2024',
    category: 'Workshop',
    featured: false,
    description: `DSI and UFIT hosted a Deep Learning Workshop at Nvidia's Auditorium in Malachowsky Hall. The workshop was led by Matt Gitzendanner and attended by 400 students. At the end of this four part series, students who successfully completed the course were able to earn an official Nvidia Deep Learning Certificate for free!`,
  },
  {
    id: 8,
    title: "DSI members win Best Overall at DataFest 2024",
    image: '/images/newsletter/datafest24/2.jpg',
    articleImage: '/images/newsletter/datafest24/1.jpg',
    date: 'April 2024',
    category: 'Competition',
    featured: false,
    description: `Eric Chao, Justin Witter, Patrick Leiman, Matheus Kunzler Maldaner and Raul Valle won Best Overall at DataFest 2024!`,
  },
  {
    id: 9,
    title: "DSI members win Best AI Hack and 2nd Place Overall at OSC Mini Hackathon",
    image: '/images/newsletter/osc-minihack24/1.png',
    articleImage: '/images/newsletter/osc-minihack24/1.png',
    date: 'March 2024',
    category: 'Competition',
    featured: false,
    description: `DSI members Matheus Kunzler Maldaner, Raul Valle and Sebastian Sosa won the Best AI Hack and 2nd Place Overall at OSC Mini Hackathon by programming a Discord Bot that can use sentiment analysis to predict when undesired content is posted in a server.`,
  },
  {
    id: 10,
    title: "DSI wins Career Influencer Award",
    image: '/images/newsletter/ccc-award25/1.jpg',
    articleImage: '/images/newsletter/ccc-award25/2.jpg',
    date: 'April 2025',
    category: 'Awards',
    featured: true,
    description: `We have recently been recognized by the UF Career Connections Center at this year's Career Influencer Awards 🎉\n\nWe extend our gratitude to the university departments that have enabled us to succeed over the past year.\nPictured are our President, Matheus Kunzler Maldaner, alongside our Internal Vice President, Ishan Kumthekar. We thank Matt Gitzendanner and Marquise M. McGriff, M.A., CCSP, also pictured, for their continuous support.\n\nWe are excited for what our new executive team will accomplish together and remain grounded in our belief that knowledge should be accessible to all. Thank you!`,
  },
  {
    id: 11,
    title: "DSI and UFIT Collaboration with HiPerGator and AI",
    image: '/images/newsletter/ufit-dsi-collab25/1.jpg',
    articleImage: '/images/newsletter/ufit-dsi-collab25/1.jpg',
    date: 'July 2025',
    category: 'Articles',
    featured: false,
    link: 'https://rc.ufl.edu/highlight-articles/ufit-collaboration-feature.html',
    description: `DSI and UFIT Research Computing are breaking barriers for accessible, hands-on AI and data science learning at UF. With HiPerGator's supercomputing power, DSI students tackle advanced projects like reimplementing Google's Titans architecture, early fire detection, and quantum-level simulations for space materials. The partnership allows students to utilize the University of Florida's supercomputer to tackle advanced projects.\n\nPictured: UFIT Research Computing training manager Matt Gitzendanner with DSI president Matheus Maldaner and Internal Vice President Ishan Kumthekar.`,
  },
  {
    id: 12,
    title: "DSI Hosts First General Body Meeting with Scott Saponas",
    image: '/images/newsletter/gbm1-25/1.png',
    articleImage: '/images/newsletter/gbm1-25/1.png',
    date: 'August 2025',
    category: 'Articles',
    featured: false,
    description: `DSI successfully hosted its first General Body Meeting of the 2025-2026 academic year, bringing together executive board members and students to discuss projects, J-board applications, upcoming HiperGator tours, and more to come.\n\nWe were privileged to host Scott Saponas, Senior Director at Microsoft Research and head of Microsoft's Undergraduate Research Internship program, who shared valuable insights about his daily work, professional journey, and answered student questions about careers in technology and research.`,
  },
  {
    id: 18,
    title: "DSI Members Win First Place at ShellHacks",
    image: '/images/newsletter/shellhacks25/2.jpg',
    articleImage: '/images/newsletter/shellhacks25/2.jpg',
    date: 'September 2025',
    category: 'Competition',
    featured: false,
    description: `Out of 1400 participants, our students Daniyal Abbasi and Joshita Arora won the first-place prize offered by Google Cloud by building BrainSafe, a browser extension that protects infant brain development by detecting harmful content in real time.\n\nBrainSafe, a browser extension powered by Google ADK, that automatically checks if content is potentially harmful and applies modifications in real time for a smoother, healthier viewing experience.\n\nThis achievement showcases the creativity and technical excellence of our members in developing solutions that make a real impact on users' digital well-being.`,
  },
  {
    id: 17,
    title: "DSI Takes on Florida's Largest Hackathon",
    image: '/images/newsletter/shellhacks25/1.jpg',
    articleImage: '/images/newsletter/shellhacks25/1.jpg',
    date: 'September 2025',
    category: 'Competition',
    featured: false,
    description: `DSI members participated in ShellHacks 2025, Florida's largest hackathon, showcasing their skills and creativity in a competitive environment.\n\nThanks to the financial support of the UF Department of Computer and Information Science and Engineering, we were able to take over 50 UF students to showcase their talent and compete at Florida's largest hackathon, hosted by INIT FIU.\n\nWe are incredibly proud of the students who participated in this three-day event.`,
  },
  {
    id: 13,
    title: "DSI members win 2nd Place Overall at OSC MiniHack 2025",
    image: '/images/newsletter/osc-minihack25/1.png',
    articleImage: '/images/newsletter/osc-minihack25/1.png',
    date: 'September 2025',
    category: 'Competition',
    featured: false,
    description: `Join us in congratulating Will Parkin, Alex Hart, Ethan Ahmed and Felix Chang for winning 2nd place overall at this year's OSC MiniHack with their project PosturePal!\n\nPosturePal uses a machine learning model to place nodes on your body (ears, neck and shoulders) with your camera. From those points, it performs calculations to know when you're slouching and provides live feedback to the user, as well as an overall posture score for the session.`,
  },
    {
      id: 14,
      title: "DSI Hosts Second General Body Meeting with Bryan Brandow",
      image: '/images/newsletter/gbm2-25/1.png',
      articleImage: '/images/newsletter/gbm2-25/1.png',
      date: 'September 2025',
      category: 'Articles',
      featured: false,
      description: `DSI hosted its second General Body Meeting of the 2025-2026 academic year, featuring exciting updates on future opportunities and a special guest speaker presentation.\n\nWe discussed upcoming workshops that DSI has been working on, a new newsletter initiative, and project proposals for the upcoming semester.\n\nWe were honored to host Bryan Brandow, a Data Engineer at OpenAI and previously at Meta, who shared insights about his day-to-day work, career journey, and answered questions from the audience about the tech industry and data engineering.`,
    },
  {
    id: 15,
    title: "Exploring UF's Supercomputing Power: HiperGator Tour",
    image: '/images/newsletter/hipergator25/1.jpg',
    articleImage: '/images/newsletter/hipergator25/1.jpg',
    date: 'September 2025',
    category: 'Articles',
    featured: false,
    description: `DSI members had the incredible opportunity to explore UF's HiperGator supercomputing facility through a series of three exclusive tours.\n\nThese tours provided students with access to one of the most powerful computing systems in academia, showcasing technology that powers innovative research across multiple disciplines.\n\nParticipants gained valuable insights into high-performance computing, learned about the facility's capabilities, and discovered how HiperGator supports research projects at UF.`,
  },
  {
    id: 21,
    title: "DSI Hosts Third General Body Meeting with Dave Brown",
    image: '/images/newsletter/gbm1-25/3.jpg',
    articleImage: '/images/newsletter/gbm1-25/3.jpg',
    date: 'October 2025',
    category: 'Articles',
    featured: false,
    description: `DSI successfully hosted its third General Body Meeting of the 2025-2026 academic year, bringing together members for updates on upcoming events and opportunities.\n\nWe were privileged to host Dave Brown, a Principal Software Engineer at Microsoft Research, who shared valuable insights about his professional experience, work at Microsoft Research, and answered student questions about careers in technology and software development.`,
  },
  {
    id: 20,
    title: "DSI members win 1st and 3rd Place at AI Days Hackathon",
    image: '/images/newsletter/ai-days25/1.png',
    articleImage: '/images/newsletter/ai-days25/1.png',
    date: 'October 2025',
    category: 'Competition',
    featured: false,
    description: `Join us in congratulating Matheus Kunzler Maldaner, Raul Valle, James Woekle, Kristian O'Connor, and Stephen Wormald for winning 1st place at this year's AI Days Hackathon with their project Plato's Cave!\n\nWe also congratulate Jaime Breitkreutz, Yimo Liu, and Max Hyken for winning 3rd place at this year's AI Days Hackathon with their project TravelBuddy AI!`,
  },
  {
    id: 19,
    title: "Internship Applyathon Recap",
    image: '/images/newsletter/applyathon25/1.png',
    articleImage: '/images/newsletter/applyathon25/1.png',
    date: 'October 2025',
    category: 'Articles',
    featured: false,
    description: `DSI members came together for our Internship Applyathon, creating a collaborative environment where students could hang out and work on job and internship applications together.\n\nMembers helped each other with application materials, shared tips and experiences, and provided mutual support throughout the application process.`,
  },
  {
    id: 16,
    title: "Michael Vega Sanz from Gail Presents to DSI Members",
    image: '/images/newsletter/speakers/gail2025.jpg',
    articleImage: '/images/newsletter/speakers/gail2025.jpg',
    date: 'October 2025',
    category: 'Articles',
    featured: false,
    description: `DSI had the pleasure of hosting Michael Vega Sanz, who spoke to our members about his company Gail and their current recruitment opportunities.\n\nGail is a financial services AI platform that allows businesses to craft their ideal workforce. The platform provides tools to develop marketing campaigns and outbound campaigns, enhances communication with visitors, and provides insights and analytics into company performance.`,
  },
];

//sort it 
export const sortedArticles = [...articles]
  .sort((a, b) => parseDate(b.date) - parseDate(a.date));
